# Animations
PLAYER_ANIMATION_DELTA = 0.05
WALLS_SPEED = 4
TILE_ANIMATION_DELTA = 0.5
ACTIVATED_ELECTRICAL_TILE_ANIMATION_DELTA = 0.05
# Scales
WALL_WIDTH, WALL_HEIGHT = 84, 121
ENLARGING_COEFFICIENT = 2
TILE_WIDTH, TILE_HEIGHT = 47, 11
# Additional
COINS_VISIBILITY_LIMIT = 5
COINS_APPEND_CHANCE = 50
COIN_ANIMATION_DELTA = 0.1
WALL_IMAGES_COUNT = 4
FPS = 30
BOSSFIGHT_TIME = 10
DRAW_HITBOXES = False
GAME_STATE_MENU = 0
GAME_STATE_PLAYING = 1
GAME_STATE_SHOP = 2
prev_main_menu_coin_animation_time = -1
current_main_menu_coin_frame = 0